{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNWB3fkI14weDtJGsHw+ZMa",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Rababalela/python-workspace/blob/main/voice%20assitant.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "t2keBiwIHs57"
      },
      "outputs": [],
      "source": [
        "n1 = \"Hello world\"\n",
        "print(n1)"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import datetime\n",
        "import webbrowser\n",
        "import math\n",
        "import json\n",
        "import urllib.request\n",
        "import random\n",
        "import operator # Import the operator module for arithmetic operations\n",
        "#______________________________________________________________________________\n",
        "# JARVIS - Personal Text Assistant\n",
        "# Autho: Tumelo\n",
        "#______________________________________________________________________________\n",
        "\n",
        "ASSISTANT_NAME = \"JARVIS\"\n",
        "reminders = [] # in-memory reminder list\n",
        "\n",
        "def greet():\n",
        "  hour = datetime.datetime.now().hour # Fixed typo: datetidatetime to datetime\n",
        "  if hour < 12:\n",
        "    period = \"Good morning\"\n",
        "  elif hour < 18:\n",
        "    period = \"Good afternoon\"\n",
        "  else:\n",
        "    period = \"Good evening\"\n",
        "  print(f\"\\n{period}! I'm {ASSISTANT_NAME}, your personal assistant\") # Added space after I'm\n",
        "  print(\"Type 'help' to see what i can do.\\n\")\n",
        "\n",
        "\n",
        "def show_help():\n",
        "  print(\"\"\"\n",
        "  ___________________________\n",
        "  COMMANDS\n",
        "  ___________________________\n",
        "  time          → Current time\n",
        "  date          → Today's date\n",
        "  calculate     → Math expression (e.g. 2**8 + sqrt(16))\n",
        "  reminder      → Set a reminder\n",
        "  reminders     → View all reminders\n",
        "  jokes         → Random joke\n",
        "  search <q>    → Google search query\n",
        "  wiki <topic>  → Open Wikipedia page\n",
        "  news          → Open Google News\n",
        "  weather <city>→ Open weather for city\n",
        "  hello         → Greeting\n",
        "  help          → Show this menu\n",
        "  quit          → Exit\n",
        "  _____________________________\n",
        "  \"\"\")\n",
        "\n",
        "def tell_time():\n",
        "  now = datetime.datetime.now().strftime(\"%H:%M:%S\")\n",
        "  print(f\"current time: {now}\")\n",
        "\n",
        "\n",
        "def tell_date():\n",
        "  Today = datetime.datetime.now().strftime(\"%d/%m/%Y\")\n",
        "  print(f\"Today's date: {Today}\")\n",
        "\n",
        "\n",
        "def calculate(expression):\n",
        "  \"\"\"Safely evaluate a math expression.\"\"\"\n",
        "  allowed = {\n",
        "      \"sqrt\": math.sqrt,\n",
        "      \"sin\": math.sin,\n",
        "      \"cos\": math.cos,\n",
        "      \"tan\": math.tan, # Added math.tan\n",
        "      \"log\": math.log,\n",
        "      \"pi\": math.pi,\n",
        "      \"e\": math.e,\n",
        "      \"**\": operator.pow, # Changed to operator.pow\n",
        "      \"*\": operator.mul,  # Changed to operator.mul\n",
        "      \"+\": operator.add,  # Changed to operator.add\n",
        "      \"-\": operator.sub,  # Changed to operator.sub\n",
        "      \"abs\": abs,\n",
        "      \"round\":round\n",
        "\n",
        "  }\n",
        "  try:\n",
        "    result = eval(expression, {\"__builtins__\":{}}, allowed)\n",
        "    print(f\"Result: {result}\")\n",
        "  except Exception as e:\n",
        "    print(f\"Error: {e}\")\n",
        "\n",
        "\n",
        "def set_reminder():\n",
        "  note = input(\"   What's the reminder? \").strip() # Removed invalid character '→'\n",
        "  if note:\n",
        "        reminders.append({\n",
        "            \"note\": note,\n",
        "            \"timestamp\": datetime.datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
        "        })\n",
        "        print(f\"Reminder saved: {note}\")\n",
        "  else:\n",
        "    print(\"Invalid reminder\")\n",
        "\n",
        "\n",
        "def view_reminders():\n",
        "  if not reminders:\n",
        "      print(\"no reminders yet.\")\n",
        "  else:\n",
        "      print(\"\\n your Reminders:\")\n",
        "      for i, r in enumerate(reminders):\n",
        "          print(f\"{i + 1}. {r['note']} - {r['timestamp']}\")\n",
        "      print()\n",
        "\n",
        "def tell_jokes():\n",
        "  jokes = [\n",
        "      \"Why do programmers prefer dark mode? Because light attracts bugs!\", # Fixed typo: Bescause\n",
        "      \"Why did python programmers break up with java? Too much class\",\n",
        "      \"How do you comfort a JavaScript bug? You console it!\",\n",
        "      \"How many programmers does it take to change a light bulb? None, its a hardware problem\", # Fixed typo: buld\n",
        "      \"Why is recursion a joke? Because why is recursion a joke?\"\n",
        "  ]\n",
        "  print(f\"aahahaha {random.choice(jokes)}\") # Added space\n",
        "\n",
        "\n",
        "def google_search(query):\n",
        "  url = f\"https://www.google.com/search?q={query.replace(' ', '+')}\"\n",
        "  webbrowser.open(url)\n",
        "  print(f\"Searching Google for: '{query}'\")\n",
        "\n",
        "def open_wikipedia(topic):\n",
        "  url = f\"https://en.wikipedia.org/wiki/{topic.replace(' ','_')}\"\n",
        "  webbrowser.open(url)\n",
        "  print(f\"Opening Wikipedia for: '{topic}'\")\n",
        "\n",
        "def open_news():\n",
        "  webbrowser.open(\"https://news.google.com/\")\n",
        "  print(\"Opening Google News...\")\n",
        "\n",
        "def open_weather(city):\n",
        "  url = f\"https://www.google.com/search?q=weather+{city}\"\n",
        "  webbrowser.open(url)\n",
        "  print(f\"Opening weather for: '{city}'\")\n",
        "\n",
        "def process_command(command):\n",
        "  cmd = command.strip().lower() # Fixed typo: commad to command\n",
        "\n",
        "  if cmd in (\"hello\", \"hi\", \"hey\"):\n",
        "    print(f\"Hello there, I'm {ASSISTANT_NAME}. How can I help you?\") # Added spaces\n",
        "\n",
        "  elif cmd == \"time\":\n",
        "    tell_time()\n",
        "  elif cmd == \"date\":\n",
        "    tell_date()\n",
        "  elif cmd == \"calculate\":\n",
        "    expression = input(\"What's the math expression?\").strip()\n",
        "    calculate(expression)\n",
        "  elif cmd == \"reminder\":\n",
        "    set_reminder()\n",
        "  elif cmd == \"reminders\":\n",
        "    view_reminders()\n",
        "  elif cmd == \"jokes\":\n",
        "    tell_jokes()\n",
        "  elif cmd.startswith(\"search\"):\n",
        "    query = command[len(\"search\"):].strip()\n",
        "    google_search(query) if query else print(\"Invalid query\")\n",
        "  elif cmd.startswith(\"wiki\"):\n",
        "    topic = command[len(\"wiki\"):].strip()\n",
        "    open_wikipedia(topic) if topic else print(\"Invalid topic\")\n",
        "  elif cmd == \"news\":\n",
        "    open_news()\n",
        "  elif cmd.startswith(\"weather \"):\n",
        "    city = command[len(\"weather\"):].strip()\n",
        "    open_weather(city) if city else print(\"Invalid city\")\n",
        "  elif cmd == \"help\":\n",
        "    show_help()\n",
        "  elif cmd in (\"quit\", \"exit\", \"bye\"):\n",
        "    print(f\"Goodbye! Have a great day.\")\n",
        "    return False  # stops the loop\n",
        "\n",
        "  else:\n",
        "     print(f\"I don't know '{command}'. Type 'help' to see available commands.\") # Fixed typo: dont to don't\n",
        "\n",
        "  return True    # Keep running\n",
        "\n",
        "\n",
        "def main():\n",
        "  greet()\n",
        "  running = True\n",
        "  while running:\n",
        "       try:\n",
        "          user_input = input(f\"{ASSISTANT_NAME} > \").strip()\n",
        "          if user_input:\n",
        "               running = process_command(user_input)\n",
        "       except KeyboardInterrupt: # Fixed capitalization: keyboardInterrupt to KeyboardInterrupt\n",
        "          print(\"\\n Goodbye!\")\n",
        "          break\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\": # Corrected indentation\n",
        "    main()"
      ],
      "metadata": {
        "id": "5_ZMxf70IS8s",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "85b2183f-b7a2-4164-ffed-ab79c817f4cd"
      },
      "execution_count": null,
      "outputs": [
        {
          "metadata": {
            "tags": null
          },
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "\n",
            "Good morning! I'm JARVIS, your personal assistant\n",
            "Type 'help' to see what i can do.\n",
            "\n",
            "aahahaha Why did python programmers break up with java? Too much class\n",
            "\n",
            "  ___________________________\n",
            "  COMMANDS\n",
            "  ___________________________\n",
            "  time          → Current time\n",
            "  date          → Today's date\n",
            "  calculate     → Math expression (e.g. 2**8 + sqrt(16))\n",
            "  reminder      → Set a reminder\n",
            "  reminders     → View all reminders\n",
            "  jokes          → Random joke\n",
            "  search <q>    → Google search query\n",
            "  wiki <topic>  → Open Wikipedia page\n",
            "  news          → Open Google News\n",
            "  weather <city>→ Open weather for city\n",
            "  hello         → Greeting\n",
            "  help          → Show this menu\n",
            "  quit          → Exit\n",
            "  _____________________________\n",
            "  \n",
            "Reminder saved: i have a class at 2 pm\n",
            "\n",
            " your Reminders:\n",
            "1. i have a class at 2 pm - 2026-04-06 11:34:49\n",
            "\n",
            "current time: 11:35:36\n",
            "current time: 11:46:43\n"
          ]
        }
      ]
    }
  ]
}